name: setup-test-lint.yml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: hexlet-components/hello-from-hexlet-action@release
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm' # ускоряет повторные сборки
      - run: npm make setup
      - run: npm make test
      - run: npm make lint
